### ISSUE TITLE
When crack login dont send to the lobby server 

### ISSUE THREAD

**Issue by turnbass** [Jakubson/JPremiumCleared#3]
hi when i login in my crack account i dont get send on the lobby server this is my config bungee and JPremium

Bungeecord config
```
prevent_proxy_connections: false
listeners:
- query_port: 25565
  motd: '&1Another Bungee server'
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  forced_hosts:
    pvp.md-5.net: pvp
  ping_passthrough: false
  priorities:
  - hub
  bind_local_address: true
  host: 0.0.0.0:25565
  max_players: 2021
  tab_size: 60
  force_default_server: true
remote_ping_cache: -1
network_compression_threshold: 256
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  - cmd.hub
  - cmd.skyblock
  - cmd.oneblock
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
  - cmd.dev
  - cmd.event
  - cmd.hub
  - cmd.skyblock
  - cmd.oneblock
log_pings: true
connection_throttle_limit: 3
server_connect_timeout: 5000
timeout: 30000
player_limit: -1
ip_forward: true
groups:
  md_5:
  - admin
remote_ping_timeout: 5000
connection_throttle: 4000
log_commands: false
stats: 538f07ba-df92-401b-b296-32bdc5bf7545
online_mode: false
forge_support: true
disabled_commands:
- disabledcommandhere
servers:
  auth:
    motd: '&1Just another BungeeCord - Forced Host'
    address: localhost:25586
    restricted: false
  hub:
    motd: '&1Just another BungeeCord - Forced Host'
    address: localhost:25587
    restricted: false
  skyblock:
    motd: '&1Just another BungeeCord - Forced Host'
    address: localhost:25548
    restricted: false
  dev:
    motd: '&1Just another BungeeCord - Forced Host'
    address: localhost:25547
    restricted: false
  event:
    motd: '&1Just another BungeeCord - Forced Host'
    address: localhost:25546
    restricted: false
  oneblock:
    motd: '&1Just another BungeeCord - Forced Host'
    address: localhost:25549
    restricted: false
  devone:
    motd: '&1Just another BungeeCord - Forced Host'
    address: localhost:25442
    restricted: false
```
    
JPremium Bungee config 

```
#+------------------------------------------------------------------------------------------------------+#
#|                                                                                                      |#
#|                                                                                                      |#
#|                                            J P R E M I U M                                           |#
#|                                        C O N F I G U R A T I O N                                     |#
#|                                                                                                      |#
#|                                                                                                      |#
#+------------------------------------------------------------------------------------------------------+#

version: 'CLEARED-Bungee-1.8.0'

# JPremium currently supports only MySQL databases.
# When JPremium cannot connect your database, issues are always produced by your database or the connection between your BungeeCord and your database!
# If you have issues, please see this wiki page: https://github.com/Jakubson/JPremiumCleared/wiki#database-issues
storageHost: *********
storagePort: 3306
storageDatabase: '***********'
storageUser: '******'
storagePassword: '*************'
storageProperties: [useSSL=true, verifyServerCertificate=true]

# Storage connection pool settings.
# Do not change these settings unless you know what you are doing!
connectionPoolSize: 10
connectionPoolIdle: 10
connectionPoolTimeout: 5000
connectionPoolLifetime: 1800000

# The mail server which is used to send mails.
# Please enter data only if you want to use the passwords recovery system.
# If you do not want to use it, please also disable the change mail address and recovery password commands.
mailHost: ''
mailPort: 25
mailUser: ''
mailPassword: ''
mailUseTLS: true

# The access token which is used to verify connections on your Spigot servers whether connections come from your BungeeCord.
# Please enter fully random unique value! Not: 'your-server-name-jpremium'!
# The same token you have to enter on all your Spigot servers.
accessToken: '3Ap6823RuibHsAX7'

# The limbo server names in your BungeeCord network.
# Not authorised players are redirected to the servers.
limboServerNames: [auth]

# The main server names in your BungeeCord network.
# Authorised players are redirected to the servers.
mainServerNames: [hub]

# What unique ids should JPremium assign for players.
# There are three options and each option has different restrictions.
# It is not recommended changing this option when some players are already registered.
# For more information, please read this wiki page: https://github.com/Jakubson/JPremiumCleared/wiki#fixed-unique-ids
uniqueIdsType: REAL

# Should JPremium force new players to register on your server, website or both side.
# There are three options to choose: 0 - server, 1 - server and website, 2 - website.
registerOnWebsite: 0

# Should JPremium register new premium players.
# When it is enabled, cracked players with premium nickname cannot join to your server.
registerPremiumUsers: true

# Should JPremium redirect players to their last server where they were before quit.
lastServerRedirection: false

# The server names in your BungeeCord network.
# Players will not be redirected to the servers as their last server.
lastServerRestrictions: [hub]

# Should JPremium redirect players to one of the main server from the server which is shutting down.
disconnectRedirection: true

# Should JPremium disconnect cracked players who enter wrong password during login.
disconnectWhenWrongPassword: true

# Should JPremium recognise Bedrock players and alters their unique ids to bedrock.
# Works only when you install GeyserMC and Floodgate on your server.
# For more information, please read this wiki page: https://github.com/Jakubson/JPremiumCleared/wiki#bedrock-support
floodgateSupport: false

# Should JPremium require to confirm a password in the register, change password and cracked commands?
# If you enable it, please do not forget to change the usage messages in the message file.
confirmPassword: false

# Should JPremium verify captcha codes which are entered by cracked players.
# If you set disable it, please also set 'captchaMapSlot' to '-1' in your JPremium configuration files on all your Spigot servers.
verifyCaptchaCode: true

# Should JPremium show a boss bar with remain time to authorisation for cracked players.
showBossBarRemainAuthorisationTimer: true

# Should JPremium keep a password when players change an account type for premium.
keepPremiumUserPasswords: false

# Should JPremium check server statuses and connect players only with online servers.
checkServerStatuses: false

# Should JPremium use the backup server when the official server is down to authorise players.
# As the backup server JPremium use CouldFlare Workers.
useBackupServer: false

# Should JPremium load user data during the login stage.
# It is an experimental feature.
loadUserProfileDataOnJoin: false

# The maximum quantity of user profiles which cracked players can register using the same IP addresses.
# When 'registerPremiumUsers' option is enabled, the limit is not apply for premium players.
maximumUserProfilesPerAddress: 2

# The maximum time (in seconds) which cracked players have for login or register.
maximumAuthorisationTime: 90

# The maximum time (in minutes) for which cracked players can start sessions?
# Sessions work only when cracked players have the same IP addresses, so it is not recommended to set the value too high.
maximumSessionTime: 1440

# The session time (in minutes) which is automatically started after cracked players login or register.
autoSessionTime: 60

# The absent time (is days) after which cracked players are automatically unregistered.
automaticUnregisterTime: 0

# The hashing algorithm which is used to hash cracked player passwords.
# There are two options: SHA256, SHA512, BCRYPT.
# All of algorithms are salted.
passwordHashingAlgorithm: SHA256

# The maximum quantity of join requests which can be processed within 3 minutes.
# If it is exceed, the next join requests are rejected.
antiBotSensitive: 120

# The safe password pattern (in regular expression). Cracked player passwords have to match to it.
safePasswordPattern: '[\S]{6,25}'

# The hostnames which players can use to connect with your BungeeCord server.
# If you want to disable it, please set the value to '[]'.
# All host names have to have ports, for example: 'acceptedHostnames: [mc.example:25565]'.
acceptedHostnames: []

# The commands which not logged cracked players can execute.
logoutUserCommands: [login, register, recoverypassword, l]

# The command aliases.
# To add more aliases for commands, please add new values using this format '<command>CommandAliases: [<alias>, <alias>, ...]', for example: 'changePasswordCommandAliases: [chpass]'.
# If you want to disable a command, you have to enter the command to the 'disabled_commands' list in your BungeeCord configuration file.
loginCommandAliases: [l]
```

and auth / lobby config 
```
#+------------------------------------------------------------------------------------------------------+#
#|                                                                                                      |#
#|                                                                                                      |#
#|                                            J P R E M I U M                                           |#
#|                                        C O N F I G U R A T I O N                                     |#
#|                                                                                                      |#
#|                                                                                                      |#
#+------------------------------------------------------------------------------------------------------+#

version: 'CLEARED-Spigot-1.8.0'

# The access token which is used to verify connections on your Spigot servers whether connections come from your BungeeCord.
# Please enter fully random unique value! Not: 'your-server-name-jpremium'!
# The same token you have to enter on your BungeeCord server.
accessToken: '3Ap6823RuibHsAX7'

# The hotbar slot number (1-9) where unregistered cracked players are given captcha maps.
# If it has -1 value, players will not receive captcha maps.
# If you enable verify captcha codes, one of your all Spigot servers has to have this value greater than -1.
captchaMapSlot: 1

# Should JPremium forbid movement of not authorised players.
forbidMovement: true

# Should JPremium forbid interactions (breaking blocks, placing blocks, attacking, chatting, etc.) of not authorised players.
forbidInteractions: true

# Should JPremium give blindness effect to not authorised players.
blindnessEffect: true

# The location where JPremium teleports all players after join.
# If you want to disable it, please set the value to ''.
# The schema of the location is world/x/y/z/yaw/pitch, for example: 'world/12/64/-32/90/18'.
spawnLocation: ''

# Players which do not send the valid access token will be disconnected with this reason.
disconnectionMessage: '&8[&c&l»&8] &7Veuillez rejoindre le serveur via &aplay.hikoami.com&7!'

# The text on captcha maps.
# You can also change the image on captcha maps by replacing 'image.png' file.
captchaMessage: 'le code est %captcha_code%
```
